config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :products

  put 'products/:id/pro' => 'products#mark_as_pro', :as => 'mark_product'
  get 'products/:id/buy' => 'products#buy_product', :as => 'buy_product'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'sign_up/admin' =>'admins#new'
  post 'sign_up/admin' =>'admins#create'

  get 'sign_up/owner' =>'owners#new'
  post 'sign_up/owner' =>'owners#create'

  get 'sign_up/guest' =>'guests#new'
  post 'sign_up/guest' =>'guests#create'

  get 'bundles/:id' => 'bundles#show', :as => 'bundle'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/new.html.slim
h2 Sign up as admin
.general-form
  = bootstrap_form_for(:admin, url: sign_up_admin_path) do |f|
    - if @admin.errors.any?
    .error_messages
      ul
        - @admin.errors.full_messages.each do |message|
          li= message
    = f.email_field :email, autofocus: true
    = f.text_field :firstname
    = f.text_field :lastname
    = f.date_field :birth_date
    = f.file_field :avatar
    = f.file_field :photo
    - if @minimum_password_length
      em
        | (#{@minimum_password_length} characters minimum)
    = f.password_field :password, autocomplete: "off"
    = f.password_field :password_confirmation, autocomplete: "off"
    .actions
      = f.submit "Sign up"
  = link_to('Sign in', '/login')