config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :products

  put 'products/:id/pro' => 'products#mark_as_pro', :as => 'mark_product'
  get 'products/:id/buy' => 'products#buy_product', :as => 'buy_product'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'sign_up/admin' =>'admins#new'
  post 'sign_up/admin' =>'admins#create'

  get 'sign_up/owner' =>'owners#new'
  post 'sign_up/owner' =>'owners#create'

  get 'sign_up/guest' =>'guests#new'
  post 'sign_up/guest' =>'guests#create'

  get 'bundles/:id' => 'bundles#show', :as => 'bundle'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bundle.rb
class Bundle < ApplicationRecord
  has_and_belongs_to_many :products

  validates :name, :price, presence: true
end

app/controllers/bundles_controller.rb
class BundlesController < ApplicationController
  before_filter :authenticate_user!

  def show
    @bundle = Bundle.find(params[:id])
    @role = session[:role]
    @show_buy_button = @role == 'guest'
  end
end

app/views/bundles/show.html.slim
p
  strong Name:
  = @bundle.name
p
  strong Price:
  = @bundle.price
table.table
  tr
    th Title
    th Description
    th Image
  - @bundle.products.each do |product|
    tr
      td= product.title
      td= product.description
      td
        img.img-rounded src = product.image
      / td= link_to 'Show', product_path(product)

p
  = link_to 'Products list', products_path
- if @show_buy_button
  p
    .btn.btn-default.btn-buy-bundle(data-bundle-id=@bundle.id) Buy bundle