config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :products

  put 'products/:id/pro' => 'products#mark_as_pro', :as => 'mark_product'
  get 'products/:id/buy' => 'products#buy_product', :as => 'buy_product'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'sign_up/admin' =>'admins#new'
  post 'sign_up/admin' =>'admins#create'

  get 'sign_up/owner' =>'owners#new'
  post 'sign_up/owner' =>'owners#create'

  get 'sign_up/guest' =>'guests#new'
  post 'sign_up/guest' =>'guests#create'

  get 'bundles/:id' => 'bundles#show', :as => 'bundle'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :bundles

  mount_uploader :image, ImageUploader
  validates :description, :title, presence: true
  # validates :image, file_size: {:maximum => 5.0.megabytes.to_i}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_user?, only: :mark_as_pro
  before_filter :owner_user?, only: [:create, :new]

  def new
  end

  def show
    @product = Product.find(params[:id])
    @role = session[:role]
    @show_buy_button = @role == 'guest' && !@product.is_pro && @product.shop
  end

  def create
    @product = Product.new(
      params.require(:product).permit(:title, :description, :image)
    )
    @product.shop = @current_user.shop
    @product.save
    redirect_to @product
  end

  def index
    @role = session[:role]
    @products = Product.where("NOT EXISTS(SELECT 1 from bundles_products where products.id = bundles_products.product_id)")
    @bundles = Bundle.all
  end

  # TODO: move to separate controller
  def mark_as_pro
    @product = Product.find_by(id: params[:id])
    @product.is_pro = true
    @product.save
    redirect_to products_path
  end

  # TODO: move to separate controller
  def buy_product
    email = @current_user.email
    return if domain_zone_com?(email)

    image_id = rand(1..5000)
    response = HTTP.get(
      "http://jsonplaceholder.typicode.com/photos/#{image_id}"
    ).to_s
    response_object = JSON.parse(response)
    return unless successful_purchase?(response_object, email)
    id_response = JSON.parse(
      HTTP.post('http://jsonplaceholder.typicode.com/todos').to_s
    )
    id = id_response['id']
    GuestMailer.purchase_email(@current_user, response_object['thumbnailUrl']).deliver_later
    AdminMailer.success_purchase_email(id).deliver_later
    render json: response
  end

  private

  def admin_user?
    return if session[:role] == 'admin'
    redirect_to products_path, alert: 'Not authorized for edit product'
  end

  def owner_user?
    return if session[:role] == 'owner'
    redirect_to products_path, alert: 'Not authorized for create product'
  end

  def domain_zone_com?(email)
    domain_zone = email.split('.').last
    return false unless domain_zone == 'com'
    response = {
      error: 'You could not buy products cause your domain zone is ".com"'
    }
    render json: response
    true
  end

  def successful_purchase?(response_object, email)
    url_value = response_object['url'].split('/').last
    thumbnail_url_value = response_object['thumbnailUrl'].split('/').last
    return true if thumbnail_url_value <= url_value
    AdminMailer.error_purchase_email(email).deliver_later
    response = {
      error: 'Sorry, but your purchase is unsuccessful. Try again later'
    }
    render json: response
    false
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.slim
h1 Listing products
table.table
  tr
    th Title
    th Description
    th Image
  - @products.each do |product|
    tr
      td= product.title
      td= product.description
      td
        img.img-rounded src = product.image
      td= link_to 'Show', product_path(product)
      - if @role == 'admin' and !product.is_pro
        td= link_to 'Mark as pro', mark_product_path(product.id), :method => :put
  - @bundles.each do |bundle|
    tr
      td= bundle.name
      td
      td
      td= link_to 'Show', bundle_path(bundle)
- if @role == 'owner'
  = link_to 'Create', new_product_path

app/views/products/new.html.slim
h2 New Product
.products-form
  = bootstrap_form_for :product, url: products_path do |f|
    = f.text_field :title
    = f.text_area :description
    = f.file_field :image
    = f.submit

app/views/products/show.html.slim
p
  strong Title:
  = @product.title
p
  strong Description:
  = @product.description
- if @role != 'guest'
  p
    strong Shop:
    = @product.shop
p
  strong Image:
  img.img-rounded src = @product.image
p
  = link_to 'Products list', products_path
- if @show_buy_button
  p
    .btn.btn-default.btn-buy-product(data-product-id=@product.id) Buy product